# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.synced_folder "backup", "/usr/share/hassio/backup/", owner: "root",  group: "root", create: true
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
    #uncomment those if you need to redirect USB devices
    # vb.customize ["modifyvm", :id, "--usb", "on"]
    # vb.customize ["modifyvm", :id, "--usbehci", "on"]
    #to find vendorid and producctid please use 'VBoxManage list usbhost'
    # vb.customize ["usbfilter", "add", "0", 
    #   "--target", :id, 
    #   "--name", "Zigbee",
    #   "--vendorid", "0x1a86",
    #   "--productid", "0x7523"]
  end

  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network "private_network", ip: "192.168.50.4"
end
