name: Bug Report
description: Do you think you have found a bug? If so then file a bug report
title: "Bug Report: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        If you haven't already, please visit the Home Assistant [Discord](https://www.home-assistant.io/join-chat/) and/or [Community Forums](https://community.home-assistant.io/) to get help before filing a bug report.
        Thank You for taking the time to fill out this bug report!
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Please Insert the output of `lsb_release -d`
      placeholder: Debian GNU/Linux 11 (bullseye)
    validations:
      required: true
  - type: input
    id: uname
    attributes:
      label: System Information
      description: Please Insert the output of `uname -a`
      placeholder: 'Linux ha-su-deb 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux'
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please explain in detail, the issue you encountered and the steps to recreate it.
      placeholder: |
        I encountered an issue when trying to upgrade my existing installation to the Debian package.
        Steps to recreate:
        1. Run the now deprecated installation script
        2. Attempt to upgrade to version 1.0.0 of the Debian package with dpkg -i as root
        3. The install will fail with the error: `dpkg-divert: error: rename involves overwriting`
    validations:
      required: true
  - type: dropdown
    id: machine-type
    attributes:
      label: Machine Type
      description: Which machine type are you running?
      options:
        - generic-x86-64
        - khadas-vim3
        - odroid-c2
        - odroid-c4
        - odroid-n2
        - odroid-xu
        - qemuarm
        - qemuarm-64
        - qemux86
        - qemux86-64
        - raspberrypi
        - raspberrypi2
        - raspberrypi3
        - raspberrypi3-64
        - raspberrypi4
        - raspberrypi4-64
        - tinker
    validations:
      required: true
  - type: textarea
    id: installer-output
    attributes:
      label: Installer output
      description: Please copy and paste any relevant output from the installer. This will be automatically formatted into code, so no need for backticks.
      render: text
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output from `journalctl -f`. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: adr
    attributes:
      label: ADR
      description: Before submitting this issue, you have read the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md).
      options:
        - label: I have read through the [ADR](https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md) and have confirmed that my system is compliant with the requirements
          required: true
        - label: I understand that if my system is found to not be compliant, my issue will be closed immediately without further investigation
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.home-assistant.io/code_of_conduct/).
      options:
        - label: I have read and agree to the [Home Assistant Code of Conduct](https://www.home-assistant.io/code_of_conduct/)
          required: true
